apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldapi
  labels:
    app: helloworldapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworldapi
  template:
    metadata:
      labels:
        app: helloworldapi
    spec:
      containers:
      - name: helloworldapi
        image: helloworldapp1020acr.azurecr.io/helloworldapi 
        ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: helloworldapisecret2